source:      .
destination: _site
includes:    ./_includes

permalink:   /:title.html

base_url: http://iamnotaprogrammer.com
#base_url: /
description: "New York Based User Experience Designer for Web Startups"
root_desc: "Colin Nederkoorn - User Experience Designer for Web Startups" 
markdown: rdiscount
highlighter: true 

rdiscount:
  extensions: []
  
exclude: ['Rakefile', 'README.markdown', 'config.rb']
