source:      .
destination: _site
includes:    ./_includes

permalink:   /:title.html

base_url: http://iamnotaprogrammer.com
#base_url: /
description: "CEO of Customer.io based in Portland, Oregon"
root_desc: "Colin Nederkoorn" 
markdown: rdiscount
highlighter: true 

rdiscount:
  extensions: []
  
exclude: ['Rakefile', 'README.markdown', 'config.rb']
