---
title: Sud0n1m.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
source: "."
destination: _site
includes: "./_includes"
permalink: "/:title.html"
base_url: http://iamnotaprogrammer.com
description: CEO of Customer.io based in Portland, Oregon
root_desc: Colin Nederkoorn
markdown: rdiscount
highlighter: true
rdiscount:
  extensions: []
exclude:
- Rakefile
- README.markdown
- config.rb
